formnya/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.iniform, name='formm'),
]

showing/urls.py
from django.urls import path
from . import views

app_name = 'showing'

urlpatterns = [
    path('', views.showing, name='create'),
    path('delete/<id>',views.delete, name='delete'),
    path('click/<id>',views.clicked, name='click')
]

story5/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.testing, name='create'),
]

story6/urls.py
from django.urls import path
from . import views

app_name = "story6"

urlpatterns = [
    path('', views.active, name='active'),
    path('delete/<id>',views.delete,name='delete')
]

tugas5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('story5.urls')),
    path('isiform/',include('formnya.urls')),
    path('jadwalku/',include('showing.urls')),
    path('activity/',include('story6.urls')),
]

formnya/models.py
from django.db import models

# Create your models here.
class Entry(models.Model):
    nama = models.CharField(max_length=30)
    dosen = models.CharField(max_length=30)
    SKS = models.CharField(max_length=30)
    deskripsi = models.CharField(max_length=30)
    semester = models.CharField(max_length=30)
    kelas = models.CharField(max_length=30)

    def __str__(self):
        return self.nama

class Deadline(models.Model):
    tugas = models.CharField(max_length=100)
    tugas_date = models.DateField()
    matkul = models.ForeignKey(Entry, on_delete=models.CASCADE)

    class Meta():
        ordering = ['tugas_date']

    def __str__(self):
        return self.tugas

showing/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.

story6/models.py
from django.db import models

# Create your models here.
class Aktivitas(models.Model):
    aktivitas = models.CharField(max_length=30)

    def __str__(self):
        return self.aktivitas

class Peserta(models.Model):
    nama = models.CharField(max_length=30)
    kegiatan = models.ForeignKey(Aktivitas, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama

formnya/forms.py
from django import forms
from .models import Entry
from django.forms import ModelForm

class MessageForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ('nama', 'dosen', 'SKS', 'deskripsi','semester','kelas')

formnya/views.py
from django.shortcuts import render, redirect
from .models import Entry
from story6.models import Aktivitas
from .forms import MessageForm

# Create your views here.
def iniform(request):
    form = MessageForm(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        formed = {
            'nama' : request.POST['nama'],
            'dosen' : request.POST['dosen'],
            'SKS' : request.POST['SKS'],
            'deskripsi': request.POST['deskripsi'],
            'semester' : request.POST['semester'],
            'kelas' : request.POST['kelas'],
            'form' : MessageForm()
        }

        new_entry = Entry(nama=formed['nama'], dosen=formed['dosen'], SKS=formed['SKS'], deskripsi=formed['deskripsi'],semester=formed['semester'],kelas=formed['kelas'])
        new_entry.save()
        new_aktiv = Aktivitas(aktivitas=request.POST['kegiatan'])
        new_aktiv.save()
        return render(request, 'form.html', formed)
    else:
        map = {
            'form' : MessageForm()
        }
        return render(request, 'form.html', map)

showing/views.py
from django.shortcuts import render, redirect
from formnya.models import Entry, Deadline

# Create your views here.
def showing(request):
    entries = Entry.objects.all()
    map = {
        'data' : entries
    }
    return render(request,'showing.html',map)

def delete(request,id):
    ent = Entry.objects.get(id = id)
    ent.delete()
    entries = Entry.objects.all()
    map = {
        'data' : entries,
    }
    return render(request, 'showing.html', map)

def clicked(request,id):
    nama = Entry.objects.get(id=id).nama
    dosen = Entry.objects.get(id=id).dosen
    SKS = Entry.objects.get(id=id).SKS
    deskripsi = Entry.objects.get(id=id).deskripsi
    semester = Entry.objects.get(id=id).semester
    kelas = Entry.objects.get(id=id).kelas

    tugas = Deadline.objects.filter(matkul = id)
    map = {
        'nama' : nama,
        'dosen' : dosen,
        'SKS' : SKS,
        'deskripsi' : deskripsi,
        'semester' : semester,
        'kelas' : kelas,
        'tugas' : tugas
    }

    return render(request,'isinya.html',map)

story5/views.py
from django.shortcuts import render


# Create your views here.

def testing(request) :
    return render(request,'index.html')

story6/views.py
from django.shortcuts import render
from .models import Aktivitas, Peserta
# Create your views here.
def active(request):
    if request.method == "POST":
        Aktiv = Aktivitas.objects.all()
        namanya = request.POST['anggota-baru']
        peserta = int(request.POST['idnya'])
        aktivitasnya = Aktivitas.objects.get(id=peserta)
        baruan = Peserta(nama=namanya, kegiatan=aktivitasnya)
        baruan.save()
        pesertanya = Peserta.objects.all()
        map = {
            'isinya' : Aktiv,
            'pesertanya' : pesertanya,
        }

        return render(request,'activity.html',map)
    else: 
        Aktiv = Aktivitas.objects.all()
        pesertanya = Peserta.objects.all()

        map = {
            'isinya' : Aktiv,
            'pesertanya' : pesertanya,
        }

        return render(request,'activity.html',map)

def delete(request,id):
    ent = Aktivitas.objects.get(id = id)
    ent.delete()
    entries = Aktivitas.objects.all()
    pesertanya = Peserta.objects.all()
    map = {
        'isinya' : entries,
        'pesertanya':pesertanya,
    }
    return render(request, 'showing.html', map)

formnya/templates/form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Story 5 Nofaldi</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <form class="box"  method="POST">
            <h1>INPUT YOUR SCHEDULE</h1>
            {% csrf_token %}
            {{ form }}
            <h4 style="color: white;">kegiatan</h4>
            <input type="text" name="kegiatan">
            <input type="submit" name="" value="Submit">
            <a href="/">Back</a>
        </form>
    </body>
    
</html>

showing/templates/isinya.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Story 5 Nofaldi</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body class="isinya">
        <p> Mata Kuliah : {{ nama }} </p>
        <p> Nama Dosen : {{ dosen }} </p>
        <p> Jumlah SKS : {{ SKS }} </p>
        <p> Deskripsi : {{ deskripsi }} </p>
        <p> Semester : {{ semester }} </p>
        <p> Kelas : {{ kelas }} </p>
        <table class="dedlen">
            {% for elemen in tugas %}
            <p>INI TUGAS LU CUK, SEBELAHNYA DEADLINENNYA</p>
            <tr>
                <td><p> {{ elemen.tugas }} </p></td>
                <td><p> {{ elemen.tugas_date }} </p></td>
            {% endfor %}
            </tr>
        </table>
       <a href="/jadwalku">Back</a>
    </body>
</html>    

showing/templates/showing.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Story 5 Nofaldi</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body class="jawaban">
        {% if not data %}
        <div class="kosongnih">
            <p>YOU DIDN'T PUT ANYTHING HERE YET</p>
            <a href="/isiform">Make Schedule</a>
            <a href="/">Back</a>
        </div>
        {% else %}
        {% for entry in data %}
        <div class="agenda">
            <a href="{% url 'showing:click' id=entry.id %}">{{entry.nama}}</a>
            <a href="{% url 'showing:delete' id=entry.id %}">Delete</a>
        </div>
        {% endfor %}
        <a href="/">Back</a>
        {% endif %}
    </body>
</html>    

story5/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Story 5 Nofaldi</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <a href="/isiform">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Create Schedule
        </a>
        <p>|</p>
        <a href=/jadwalku>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Show Schedule
        </a>
        <p>|</p>
        <a href="/activity">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            My Activity
        </a>
    </body>
</html>

story6/templates/activity.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Story 5 Nofaldi</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body class="bodynya">
        {% if not isinya %}
        <div class="kosongnih1">
            <p>YOU DIDN'T PUT ANYTHING HERE YET</p>
            <a href="/isiform">Make Schedule</a>
            <a href="/">Back</a>
        </div>
        {% else %}
        <a href="/" class="mundurin">Back</a>
        <div class="content">
          {% for x in isinya %}
          <div class="boxed">
            <h1>{{ x.aktivitas }}</h1>
            <h3>{{ x.waktu }}</h3>
            {% for y in pesertanya %}
            {% if y.kegiatan == x %}
            <p>{{y.nama}}</p>
            {% endif %}
            {% endfor %}
            <form action="/activity/" method="POST">
              {% csrf_token %}
              <input type="text" name="anggota-baru" placeholder="Type Your Name" class="box-1-text-2">
              <input type="text" name="idnya" class="ilangnih" value="{{ x.id }}">
              <input type="submit" class="isian-aktivitas" value="add">
            </form>
            <a href="{% url 'story6:delete' id=x.id %}">Delete</a>
          </div>
          {% endfor %}
          {% endif %}
        </div>
    </body>
</html>